[package]
name = "db-rs"
version = "0.1.13"
edition = "2021"
description = "fast, embedded, transactional, key value store"
license = "BSD-3-Clause"
readme = "../README.md"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"

[dev-dependencies]
db-rs-derive = { path = "../derive" }
